FROM nginx

WORKDIR /etc/ssl

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

COPY .nginx/ssl/ssl.conf ssl.conf

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -config ssl.conf -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

